name: Sync with songquanpeng/one-api

permissions:
  contents: write
  issues: write
  actions: write

on:
  schedule:
    - cron: '0 * * * *' # every day at midnight
  workflow_dispatch:

jobs:
  sync_with_upstream:
    name: Sync latest commits from songquanpeng/one-api
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - uses: actions/checkout@v4

      - name: Clean issue notice
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issues'
          labels: '🚨 Sync Fail'

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: songquanpeng/one-api
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-issue'
          title: '🚨 同步失败 | Sync Fail'
          labels: '🚨 Sync Fail'
          body: |
            由于 songquanpeng/one-api 仓库的变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，请查看详细教程。

            Due to changes in the songquanpeng/one-api repository, GitHub has automatically suspended this automatic update. You need to manually sync your fork once. Please refer to the detailed tutorial for instructions.
